version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/html
      - ../default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build:
      dockerfile: .docker/Dockerfile
      context: ../
    volumes:
      - ../:/var/www/html
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: app
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
